name: 'Pull request updater'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - main
      - 'releases/*'
jobs:
  check-commit-message:
    name: update description
    runs-on: ubuntu-latest
    steps:
      - name: update description
        uses: cleiltonoliveira/pr-updater@v1.2
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }} 
