name: 'Pull request updater'
on:
  pull_request:
    types:
      - opened
 # pull_request_target:
 #   types:
  #    - opened
  #    - edited
   #   - reopened
  #    - synchronize
 # push:
  #  branches:
  #    - main
   #   - 'releases/*'
jobs:
  pr-updater:
    name: update description
    runs-on: ubuntu-latest
    steps:
      - name: update description
        uses: cleiltonoliveira/pr-updater@main
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }} 
